"""users table

Revision ID: 8e312795f901
Revises: 
Create Date: 2020-03-23 14:37:18.864957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e312795f901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('follow_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=140), nullable=True),
    sa.Column('overall_problem', sa.String(length=10000), nullable=True),
    sa.Column('headaches', sa.String(length=20), nullable=True),
    sa.Column('headaches_frequency', sa.String(length=1000), nullable=True),
    sa.Column('headaches_length', sa.String(length=1000), nullable=True),
    sa.Column('headaches_spots', sa.String(length=20), nullable=True),
    sa.Column('headaches_flashes', sa.String(length=20), nullable=True),
    sa.Column('headaches_medication', sa.String(length=1000), nullable=True),
    sa.Column('dizziness', sa.String(length=20), nullable=True),
    sa.Column('unsteady_gait', sa.String(length=20), nullable=True),
    sa.Column('neck_pain', sa.String(length=20), nullable=True),
    sa.Column('neck_pain_shoulders', sa.String(length=20), nullable=True),
    sa.Column('neck_pain_arms', sa.String(length=20), nullable=True),
    sa.Column('back_pain', sa.String(length=20), nullable=True),
    sa.Column('back_pain_hips', sa.String(length=20), nullable=True),
    sa.Column('back_pain_legs', sa.String(length=20), nullable=True),
    sa.Column('back_pain_right_side', sa.String(length=20), nullable=True),
    sa.Column('back_pain_left_side', sa.String(length=20), nullable=True),
    sa.Column('arm_pain', sa.String(length=20), nullable=True),
    sa.Column('arm_pain_right_side', sa.String(length=20), nullable=True),
    sa.Column('arm_pain_left_side', sa.String(length=20), nullable=True),
    sa.Column('leg_pain', sa.String(length=20), nullable=True),
    sa.Column('leg_pain_right_side', sa.String(length=20), nullable=True),
    sa.Column('leg_pain_left_side', sa.String(length=20), nullable=True),
    sa.Column('fingers', sa.String(length=20), nullable=True),
    sa.Column('hands', sa.String(length=20), nullable=True),
    sa.Column('feet', sa.String(length=20), nullable=True),
    sa.Column('legs', sa.String(length=20), nullable=True),
    sa.Column('numbness_right_side', sa.String(length=20), nullable=True),
    sa.Column('numbness_left_side', sa.String(length=20), nullable=True),
    sa.Column('fainting', sa.String(length=20), nullable=True),
    sa.Column('fainting_frequency', sa.String(length=1000), nullable=True),
    sa.Column('fainting_length', sa.String(length=1000), nullable=True),
    sa.Column('seizure', sa.String(length=20), nullable=True),
    sa.Column('seizure_frequency', sa.String(length=1000), nullable=True),
    sa.Column('seizure_length', sa.String(length=1000), nullable=True),
    sa.Column('seizure_medication', sa.String(length=1000), nullable=True),
    sa.Column('limb_jerking', sa.String(length=20), nullable=True),
    sa.Column('tremors', sa.String(length=20), nullable=True),
    sa.Column('tremors_hands', sa.String(length=20), nullable=True),
    sa.Column('tremors_legs', sa.String(length=20), nullable=True),
    sa.Column('tremors_positions', sa.String(length=1000), nullable=True),
    sa.Column('sleep_difficulties', sa.String(length=20), nullable=True),
    sa.Column('increased_stress', sa.String(length=20), nullable=True),
    sa.Column('episodes_of_confusion', sa.String(length=20), nullable=True),
    sa.Column('episodes_of_confusion_optional', sa.String(length=1000), nullable=True),
    sa.Column('memory_problems', sa.String(length=20), nullable=True),
    sa.Column('hospital_recently', sa.String(length=20), nullable=True),
    sa.Column('hospital_recently_optional', sa.String(length=1000), nullable=True),
    sa.Column('medication_change', sa.String(length=20), nullable=True),
    sa.Column('medication_change_optional', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_timestamp'), 'follow_up', ['timestamp'], unique=False)
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=140), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('hand', sa.String(length=10), nullable=True),
    sa.Column('referred_by', sa.String(length=1000), nullable=True),
    sa.Column('reason_for_visit', sa.String(length=10000), nullable=True),
    sa.Column('limb_jerking', sa.String(length=20), nullable=True),
    sa.Column('tremors', sa.String(length=20), nullable=True),
    sa.Column('depression', sa.String(length=20), nullable=True),
    sa.Column('headaches', sa.String(length=20), nullable=True),
    sa.Column('sleep_difficulties', sa.String(length=20), nullable=True),
    sa.Column('increased_stress', sa.String(length=20), nullable=True),
    sa.Column('memory_problems', sa.String(length=20), nullable=True),
    sa.Column('back_neck_pain', sa.String(length=20), nullable=True),
    sa.Column('numbness', sa.String(length=20), nullable=True),
    sa.Column('numbness_optional', sa.String(length=20), nullable=True),
    sa.Column('head_injury', sa.String(length=20), nullable=True),
    sa.Column('dizziness', sa.String(length=20), nullable=True),
    sa.Column('unsteady_gait', sa.String(length=20), nullable=True),
    sa.Column('balance_difficulties', sa.String(length=20), nullable=True),
    sa.Column('fainting', sa.String(length=20), nullable=True),
    sa.Column('word_finding', sa.String(length=20), nullable=True),
    sa.Column('episodes_of_confusion', sa.String(length=20), nullable=True),
    sa.Column('hospital_recently', sa.String(length=20), nullable=True),
    sa.Column('medication_change', sa.String(length=20), nullable=True),
    sa.Column('other_symptoms', sa.String(length=10000), nullable=True),
    sa.Column('hypertension', sa.String(length=20), nullable=True),
    sa.Column('heart_problems', sa.String(length=20), nullable=True),
    sa.Column('diabetes_mellitus', sa.String(length=20), nullable=True),
    sa.Column('high_cholesterol', sa.String(length=20), nullable=True),
    sa.Column('stroke', sa.String(length=20), nullable=True),
    sa.Column('seizure', sa.String(length=20), nullable=True),
    sa.Column('depression_disease', sa.String(length=20), nullable=True),
    sa.Column('migraine', sa.String(length=20), nullable=True),
    sa.Column('cigarettes', sa.String(length=20), nullable=True),
    sa.Column('cigarettes_long', sa.String(length=1000), nullable=True),
    sa.Column('cigarettes_frequency', sa.String(length=1000), nullable=True),
    sa.Column('alcohol', sa.String(length=20), nullable=True),
    sa.Column('drugs', sa.String(length=20), nullable=True),
    sa.Column('weight_loss', sa.String(length=20), nullable=True),
    sa.Column('fever', sa.String(length=20), nullable=True),
    sa.Column('palpitation', sa.String(length=20), nullable=True),
    sa.Column('chest_pain', sa.String(length=20), nullable=True),
    sa.Column('cough', sa.String(length=20), nullable=True),
    sa.Column('sputum', sa.String(length=20), nullable=True),
    sa.Column('abdominal_pain', sa.String(length=20), nullable=True),
    sa.Column('nausea', sa.String(length=20), nullable=True),
    sa.Column('vomiting', sa.String(length=20), nullable=True),
    sa.Column('diarrhea', sa.String(length=20), nullable=True),
    sa.Column('hematuria', sa.String(length=20), nullable=True),
    sa.Column('urination_incontinence', sa.String(length=25), nullable=True),
    sa.Column('over_eating', sa.String(length=20), nullable=True),
    sa.Column('over_urinating', sa.String(length=20), nullable=True),
    sa.Column('over_sweating', sa.String(length=20), nullable=True),
    sa.Column('always_thirsty', sa.String(length=20), nullable=True),
    sa.Column('skin_rash', sa.String(length=20), nullable=True),
    sa.Column('lesion', sa.String(length=20), nullable=True),
    sa.Column('easily_bleeds', sa.String(length=20), nullable=True),
    sa.Column('bruises', sa.String(length=20), nullable=True),
    sa.Column('blood_clots', sa.String(length=20), nullable=True),
    sa.Column('joint_pain', sa.String(length=20), nullable=True),
    sa.Column('muscle_pain', sa.String(length=20), nullable=True),
    sa.Column('elaborate', sa.String(length=10000), nullable=True),
    sa.Column('occupation', sa.String(length=1000), nullable=True),
    sa.Column('surgeries', sa.String(length=10000), nullable=True),
    sa.Column('medication_allergies', sa.String(length=10000), nullable=True),
    sa.Column('family_medical_problems', sa.String(length=10000), nullable=True),
    sa.Column('current_medications', sa.String(length=10000), nullable=True),
    sa.Column('other_information', sa.String(length=10000), nullable=True),
    sa.Column('patient_signature', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_timestamp'), 'form', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_timestamp'), table_name='form')
    op.drop_table('form')
    op.drop_index(op.f('ix_follow_up_timestamp'), table_name='follow_up')
    op.drop_table('follow_up')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
