from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import User

class MedicalForm(FlaskForm):
    patient_name = StringField('Patient Name', validators=[DataRequired()])
    sex = StringField('Sex', validators=[DataRequired()])
    #date_of_birth = DateField('Date of Birth', validators=[DataRequired()])
    date_of_birth = StringField('Date of Birth (ex 10/13/1980)' , validators=[DataRequired()])
    age = IntegerField('Age', validators=[DataRequired()])
    height = StringField('Height', validators=[DataRequired()])
    weight = IntegerField('Weight', validators=[DataRequired()])
    hand = RadioField('Right or left handed?', choices=[('Right', 'Right handed'),('Left','Left handed')], validators=[DataRequired()])
    referred_by = StringField('Referred By')
    #Symptoms
    reason_for_visit = StringField('Reason for visit')
    limb_jerking = RadioField('Limb jerking', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    tremors = RadioField('Tremors', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    depression = RadioField('Feelings of unhappiness/depression', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    headaches = RadioField('Headaches', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    sleep_difficulties = RadioField('Sleep difficulties', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    increased_stress = RadioField('Increased stress', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    memory_problems = RadioField('Memory problems', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    back_neck_pain = RadioField('Back/neck pain', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    numbness = RadioField('Numbess/tingling in limbs', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    numbness_optional = StringField('If yes please describe:')
    head_injury = RadioField('Head injury or concussion', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    dizziness = RadioField('Dizziness', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    unsteady_gait = RadioField('Unsteady gait', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    balance_difficulties = RadioField('Balance difficulties', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    fainting = RadioField('Episodes of fainting/blacking out', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    word_finding = RadioField('Episodes of word finding difficulties', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    episodes_of_confusion = RadioField('Episodes of confusion', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    hospital_recently = RadioField('Have you visited the ER/Hospital recently?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    medication_change = RadioField('Have you recently had any medication changes?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    other_symptoms = StringField('Other symptoms not listed')
    #conditions
    hypertension = RadioField('Hypertension', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    heart_problems = RadioField('Heart problems', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    diabetes_mellitus = RadioField('Diabetes Mellitus', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    high_cholesterol = RadioField('High cholesterol', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    stroke = RadioField('Stroke', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    seizure = RadioField('Seizure', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    depression_disease = RadioField('Depression', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    migraine = RadioField('Migraine', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    #habits
    cigarettes = RadioField('Do you smoke cigarettes?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    cigarettes_long = StringField('If yes, for how long have you been smoking?')
    cigarettes_frequency = StringField('If yes, how frequently? (ex - # of packs a day)')
    alcohol = RadioField('Do you drink alcoholic beverages?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    drugs = RadioField('Do you use recreational drugs?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    #begin medical systems
    #constitutional
    weight_loss = BooleanField('Recent weight loss')
    fever = BooleanField('Fever')
    #cardiovascular
    palpitation = BooleanField('Palpitation')
    chest_pain = BooleanField('Chest pain')
    #pulmonary
    cough = BooleanField('Cough')
    sputum = BooleanField('Sputum')
    #gastrointestinal
    abdominal_pain = BooleanField('Abdominal pain')
    nausea = BooleanField('Nausea')
    vomiting = BooleanField('Vomiting')
    diarrhea = BooleanField('Diarrhea')
    #genital urinary
    hematuria = BooleanField('Hematuria')
    urination_incontinence = BooleanField('Urination incontinence')
    #endocrinological
    over_eating = BooleanField('Overeating')
    over_urinating = BooleanField('Over-urinating')
    over_sweating = BooleanField('Over-sweating')
    always_thirsty = BooleanField('Always thirsty')
    #dermatological
    skin_rash = BooleanField('Skin rash')
    lesion = BooleanField('Lesion')
    #hematological
    easily_bleeds = BooleanField('Easily bleeds')
    bruises = BooleanField('Bruises')
    blood_clots = BooleanField('Blood clots')
    #skeletal musculary
    joint_pain = BooleanField('Joint pain')
    muscle_pain = BooleanField('Muscle pain')
    #extra
    elaborate = StringField('If any elaboration needed for these symptoms needed or a symptom is not listed, do so here.')
    #end medical systems
    #misc
    occupation = StringField('Occupation')
    surgeries = StringField('Please list any surgeries')
    medication_allergies = StringField('Please list any medication allergies')
    family_medical_problems = StringField('Please list any known family medical problems. If applicable, please specify from what side of your family (mother, father, etc)')
    current_medications = StringField('Please list all the medications you are currently taking:')
    other_information = StringField('Any other information you would like the doctor to know?')
    patient_signature = StringField('Patient signature. Please type first and last name.', validators=[DataRequired()])
    submit = SubmitField('Submit')

class FollowUpForm(FlaskForm):
    patient_name = StringField('Patient Name', validators=[DataRequired()])
    overall_problem = StringField('*What neurological problem do you have? What symptoms do you have and require help/treatment? Please describe.', validators=[DataRequired()])
    headaches = RadioField('Do you have headaches?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    headaches_frequency = StringField('If yes, how many headaches a month?')
    headaches_length = StringField('About how long does each headache last? (ex - 30 minutes)')
    headaches_spots = BooleanField('Spots')
    headaches_flashes = BooleanField('Flashes of light')
    headaches_medication = StringField('What medications for headaches have you tried? Was it helpful?')
    dizziness = RadioField('Do you have dizziness?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    unsteady_gait = RadioField('Do you have episodic unsteady gait?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    neck_pain = RadioField('Do you have neck pain?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    neck_pain_shoulders = BooleanField('Shoulders')
    neck_pain_arms = BooleanField('Arms')
    back_pain = RadioField('Do you have lower back pain?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    back_pain_hips = BooleanField('Hips')
    back_pain_legs = BooleanField('Legs')
    back_pain_right_side = BooleanField('Right')
    back_pain_left_side = BooleanField('Left')
    arm_pain = RadioField('Do you have arm pain?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    arm_pain_right_side = BooleanField('Right')
    arm_pain_left_side = BooleanField('Left')
    leg_pain = RadioField('Do you have leg pain?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    leg_pain_right_side = BooleanField('Right')
    leg_pain_left_side = BooleanField('Left')
    #numbness/tingling
    fingers = BooleanField('Fingers')
    hands = BooleanField('Hands')
    feet = BooleanField('Feet')
    legs = BooleanField('Legs')
    numbness_right_side = BooleanField('Right')
    numbness_left_side = BooleanField('Left')
    #fainting
    fainting = RadioField('*Do you have episodes of fainting/blacking out?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    fainting_frequency = StringField('How many times?')
    fainting_length = StringField('Lasting how long?')
    #Seizure
    seizure = RadioField('Do you have seizure episodes?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    seizure_frequency = StringField('How many times?')
    seizure_length = StringField('Lasting how long?')
    seizure_medication = StringField('If you are on seizure medication, which one? Are you missing any doses?')
    #tremors/limb jerking
    limb_jerking = RadioField('Do you have limb jerking?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    tremors = RadioField('Do you have tremors?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    tremors_hands = BooleanField('Hands')
    tremors_legs = BooleanField('Legs')
    tremors_positions = StringField('Do the tremors occur in a resting position or a specific position? (ex - holding a glass of water)')
    sleep_difficulties = RadioField('Do you have sleep difficulties?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    increased_stress = RadioField('Have you had an increased stress level?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    episodes_of_confusion = RadioField('Have you had episodes of confusion?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    episodes_of_confusion_optional = StringField('If yes, how often?')
    memory_problems = RadioField('Do you have memory problems?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    hospital_recently = RadioField('Have you visited the ER/Hospital recently?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    hospital_recently_optional = StringField('If yes, how long did you stay?')
    medication_change = RadioField('Have you recently had any medication changes?', choices=[('Yes', 'Yes'),('No','No')], validators=[DataRequired()])
    medication_change_optional = StringField('If yes, what medication did you start using and what medication did you stop using?')
    submit = SubmitField('Submit')
